### ISSUE TITLE
Support for prompt chaining?

### ISSUE THREAD

**Issue by merchako** [yohasebe/openai-text-completion-workflow#12]
Does this workflow support prompt chaining?
If not, I would love to have it as a feature. 
If so, could you mention it in the README with an example?

**Comment by yohasebe** [comment]
Thank you for reaching out to me. Currently, I don’t plan to add support for prompt chaining in this workflow.

However, I am working on a new project involving an OpenAI chat API web interface running on Docker. I will create an Alfred workflow for this new app, allowing you to do many things, including prompt chaining, data import/export, voice recognition, speech-to-text, etc. I hope you try it out once it's been released!
