### ISSUE TITLE
Add Support for GPT-3.5-Turbo Model

### ISSUE THREAD

**Issue by XOKP** [yohasebe/openai-text-completion-workflow#2]
I suggest that support for the gpt-3.5-turbo model be added, as it is the latest and more affordable model with significantly lower costs.

**Comment by yohasebe** [comment]
I have released version 1.6.0 with support for ChatGPT API and `gpt-3.5-turbo` as default model. Enjoy!

**Comment by XOKP** [comment]
Thank you so much for adding support for gpt-3.5-turbo model in the latest release! Looking forward to trying out the new default model. Keep up the excellent work, you are the best!
